### ISSUE TITLE
compare to j2v8 

### ISSUE THREAD

**Issue by TIIEHenry** [ancientloregames/AndroidJavaScriptCore#1] opened 2019-09-15 14:50 UTC
I've been working on j2v8 recently，But the inability to pass Java objects bothered me ，So will it help me solve the problem？

**Comment by ancientloregames** [comment] 2019-09-26 08:20
Sorry for taking so long to answer. Please, specify your question. If you are talking about exporting of an object to the JS context with it's methods and fields, then yes, it's possible. There is an abstract class JSProxy. When you extend your class with JSProxy, add the jsexport annotation to all methods and fileds you want to be present in the resulting JS object. There is also the JSProperty class for fields
you want to be able to set/get from both sides, but currently, there is an issue with it, that I'm working on.
Here is a quick example:
```
public class ExampleProxy extends JSProxy {

    @jsexport
    public int a;

    public JSProperty<Boolean> b;

    public ExampleProxy(JSContext context) {
        super(context);
    }

    public ExampleProxy(JSContext context, int exportTarget) {
        super(context, exportTarget);
    }

    @jsexport
    public void c()
    {
        Log.i("qwerty", "c called");
    }
}

// Instantiation example

public void example() {
	JSContext context = new JSContext();
	ExampleProxy proxy = new ExampleProxy(context);
	context.property("proxy", proxy);
	JSValue jsProxy = context.property("proxy");
}
```

**Comment by ancientloregames** [comment] 2019-10-03 13:20
I'll presume that my answer is sufficient enough, hence close this issue.

P.S. JSProperty is now working as intended.

**Closed as completed by ancientloregames** 2019-10-03 13:20 UTC

**Comment by TIIEHenry** [comment] 2020-02-09 04:45
thanks for your answer
